from pathlib import Path
path = Path('src/pages/Pengajuan.tsx')
text = path.read_text()
old = "{TABLE_COLUMNS.map((column) => (\r\n                <div\r\n                  role=\"columnheader\"\r\n                  key={`head-${column.key}`}\r\n                  className={`${column.align} ${column.justify} ${column.headPadding} py-2 flex items-center`}\r\n                  style={getColumnFlexStyles(column)}\r\n                >\r\n                  {column.sortable ? (\r\n                    <button\r\n                      onClick={() => handleSort(column.sortKey ?? column.key)}\r\n                      className={`flex w-full items-center gap-1 hover-text-foreground ${column.justify}`}\r\n                    >\r\n                      <span className={`${HEADER_TEXT_PADDING} flex-1`}>{column.label}</span>\r\n                      <span className=\"ml-1 shrink-0\">\r\n                        <ChevronsUpDown className=\"h-2.5 w-2.5 text-muted-foreground/80\" />\r\n                      </span>\r\n                    </button>\r\n                  ) : (\r\n                    <div className={`flex w-full items-center ${column.justify}`}>\r\n                      <span className={HEADER_TEXT_PADDING}>{column.label}</span>\r\n                    </div>\r\n                  )}\r\n                </div>\r\n              ))"
new = "{TABLE_COLUMNS.map((column) => (\r\n                <div\r\n                  role=\"columnheader\"\r\n                  key={`head-${column.key}`}\r\n                  className={`${column.align} ${column.justify} ${column.headPadding} py-2 flex items-center`}\r\n                  style={getColumnFlexStyles(column)}\r\n                >\r\n                  {column.sortable ? (\r\n                    <button\r\n                      onClick={() => handleSort(column.sortKey ?? column.key)}\r\n                      className={`flex w-full items-center gap-[2px] hover:text-foreground ${column.justify}`}\r\n                    >\r\n                      {column.label}\r\n                      <ChevronsUpDown className=\"h-2.5 w-2.5 text-muted-foreground/80\" />\r\n                    </button>\r\n                  ) : (\r\n                    <div className={`flex w-full items-center ${column.justify}`}>{column.label}</div>\r\n                  )}\r\n                </div>\r\n              ))"
if old not in text:
    raise SystemExit('old snippet not found')
text = text.replace(old, new, 1)
path.write_text(text)
