// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wogqcjlwelepqykkbcdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvZ3Fjamx3ZWxlcHF5a2tiY2RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNjk4NDIsImV4cCI6MjA3MDY0NTg0Mn0.Yw47Zl9INgaYJhKDXwYKx3iQRhpSzn3kcQUOhFnlQ-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});